name = "openglada_examples"
description = "OpenGLAda examples (not intended to be published as crate)"
version = "0.9.0"

authors = ["Roger Mc Murtrie", "Felix Krause"]
maintainers = ["Felix Krause <contact@flyx.org>"]
maintainers-logins = ["flyx"]
project-files = [
      "durian/buffers_and_textures/buffers_and_textures.gpr",
      "durian/hello/hello_durian.gpr",
      "ogl_tutorials/02_red_triangle/tutorial_02.gpr",
      "ogl_tutorials/03_matrices/tutorial_03.gpr",
      "ogl_tutorials/04_coloured_cube/tutorial_04.gpr",
      "ogl_tutorials/05_textured_cube/tutorial_05.gpr",
      "ogl_tutorials/06_keyboard_mouse/tutorial_06.gpr",
      "ogl_tutorials/07_model_loading/tutorial_07.gpr",
      "ogl_tutorials/08_basic_shading/tutorial_08.gpr",
      "ogl_tutorials/09_vbo_indexing/tutorial_09.gpr",
      "ogl_tutorials/external_wave/wave.gpr",
      "ogl_tutorials/indexed_model_loading/indexing.gpr",
      "ogl_tutorials/misc05_picking_easy/misc_05.gpr",
      "open_gl/coloured_elements/element_buffers.gpr",
      "open_gl/feedback_query/transform.gpr",
      "open_gl/simple_uniform/simple_uniform.gpr",
      "open_gl/square/coloured_square.gpr",
      "open_gl/very_simple/simple_triangle.gpr",
      "redbook/03_draw_commands/draw_commands.gpr",
      "redbook/03_instancing/instancing_example.gpr",
      "superbible/fragment_colouring/fragment_colouring.gpr",
      "superbible/moving_triangle/moving_triangle.gpr",
      "superbible/rotating_squares/rotating_squares.gpr",
      "superbible/simple_texture/simple_texture.gpr",
      "superbible/simplest/just_a_dot.gpr",
      "superbible/spinning_cubes/spinning_cubes.gpr",
      "superbible/tess/simple_tessellation.gpr",
      "superbible/tessellation_with_geometry/simple_tessellation_with_geometry.gpr",
      "superbible/tumbling_squares/tumbling_squares.gpr",
      "superbible/vertex_colouring/vertex_colouring.gpr"]

executables = [
      "durian/buffers_and_textures/buffers_and_textures",
      "durian/hello/hello_durian",
      "ogl_tutorials/02_red_triangle/tutorial_02",
      "ogl_tutorials/03_matrices/tutorial_03",
      "ogl_tutorials/04_coloured_cube/tutorial_04",
      "ogl_tutorials/05_textured_cube/tutorial_05",
      "ogl_tutorials/06_keyboard_mouse/tutorial_06",
      "ogl_tutorials/07_model_loading/tutorial_07",
      "ogl_tutorials/08_basic_shading/tutorial_08",
      "ogl_tutorials/09_vbo_indexing/tutorial_09",
      "ogl_tutorials/external_wave/wave",
      "ogl_tutorials/indexed_model_loading/indexing",
      "ogl_tutorials/misc05_picking_easy/misc_05",
      "open_gl/coloured_elements/element_buffers",
	  "open_gl/feedback_query/transform",
      "open_gl/simple_uniform/simple_uniform",
      "open_gl/square/coloured_square",
      "open_gl/very_simple/simple_triangle",
      "redbook/03_draw_commands/draw_commands",
      "redbook/03_instancing/instancing_example",
      "superbible/fragment_colouring/fragment_colouring",
      "superbible/moving_triangle/moving_triangle",
      "superbible/rotating_squares/rotating_squares",
      "superbible/simple_texture/simple_texture",
      "superbible/simplest/just_a_dot",
      "superbible/spinning_cubes/spinning_cubes",
      "superbible/tess/simple_tessellation",
      "superbible/tessellation_with_geometry/simple_tessellation_with_geometry",
      "superbible/tumbling_squares/tumbling_squares",
      "superbible/vertex_colouring/vertex_colouring"]

[[depends-on]]
openglada = "~0.9.0"
openglada_glfw = "~0.9.0"
openglada_images = "~0.9.0"
openglada_text = "~0.9.0"
